version: "2.0"
services:
  influxdb:
    image: influxdb:1.8
    ports: [ "0.0.0.0:8086:8086" ]
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=water_meter
    restart: unless-stopped
